// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4E25CVCLDVZsqhHjIKq-aClGMoKrw64',
    appId: '1:926515196151:web:f672aa67cc76e4928ae3f2',
    messagingSenderId: '926515196151',
    projectId: 'maskenote-ed4f5',
    authDomain: 'maskenote-ed4f5.firebaseapp.com',
    storageBucket: 'maskenote-ed4f5.appspot.com',
    measurementId: 'G-NVTGXWDV75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKzLDWH4BWYVb2V6SWGyA4c1oysvcvjA',
    appId: '1:926515196151:android:6dd867d47a0770c28ae3f2',
    messagingSenderId: '926515196151',
    projectId: 'maskenote-ed4f5',
    storageBucket: 'maskenote-ed4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4DNSBZwIzxddR-RVXicXGIpm9rjSqw4c',
    appId: '1:926515196151:ios:845aa7bcf3fba7468ae3f2',
    messagingSenderId: '926515196151',
    projectId: 'maskenote-ed4f5',
    storageBucket: 'maskenote-ed4f5.appspot.com',
    iosBundleId: 'com.example.primaprova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4DNSBZwIzxddR-RVXicXGIpm9rjSqw4c',
    appId: '1:926515196151:ios:960f7776c9d4c9fe8ae3f2',
    messagingSenderId: '926515196151',
    projectId: 'maskenote-ed4f5',
    storageBucket: 'maskenote-ed4f5.appspot.com',
    iosBundleId: 'com.example.primaprova.RunnerTests',
  );
}
